/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedSubscriptionsIndexRouteImport } from './routes/_authed/subscriptions/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedSubscriptionsNewRouteImport } from './routes/_authed/subscriptions/new'
import { Route as AuthedSubscriptionsIdRouteImport } from './routes/_authed/subscriptions/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSubscriptionsIndexRoute =
  AuthedSubscriptionsIndexRouteImport.update({
    id: '/subscriptions/',
    path: '/subscriptions/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSubscriptionsNewRoute = AuthedSubscriptionsNewRouteImport.update({
  id: '/subscriptions/new',
  path: '/subscriptions/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSubscriptionsIdRoute = AuthedSubscriptionsIdRouteImport.update({
  id: '/subscriptions/$id',
  path: '/subscriptions/$id',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/subscriptions/$id': typeof AuthedSubscriptionsIdRoute
  '/subscriptions/new': typeof AuthedSubscriptionsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/subscriptions/': typeof AuthedSubscriptionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/subscriptions/$id': typeof AuthedSubscriptionsIdRoute
  '/subscriptions/new': typeof AuthedSubscriptionsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/subscriptions': typeof AuthedSubscriptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/subscriptions/$id': typeof AuthedSubscriptionsIdRoute
  '/_authed/subscriptions/new': typeof AuthedSubscriptionsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/subscriptions/': typeof AuthedSubscriptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/subscriptions/$id'
    | '/subscriptions/new'
    | '/api/auth/$'
    | '/subscriptions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/subscriptions/$id'
    | '/subscriptions/new'
    | '/api/auth/$'
    | '/subscriptions'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/dashboard'
    | '/_authed/subscriptions/$id'
    | '/_authed/subscriptions/new'
    | '/api/auth/$'
    | '/_authed/subscriptions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/subscriptions/': {
      id: '/_authed/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions/'
      preLoaderRoute: typeof AuthedSubscriptionsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/subscriptions/new': {
      id: '/_authed/subscriptions/new'
      path: '/subscriptions/new'
      fullPath: '/subscriptions/new'
      preLoaderRoute: typeof AuthedSubscriptionsNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/subscriptions/$id': {
      id: '/_authed/subscriptions/$id'
      path: '/subscriptions/$id'
      fullPath: '/subscriptions/$id'
      preLoaderRoute: typeof AuthedSubscriptionsIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedSubscriptionsIdRoute: typeof AuthedSubscriptionsIdRoute
  AuthedSubscriptionsNewRoute: typeof AuthedSubscriptionsNewRoute
  AuthedSubscriptionsIndexRoute: typeof AuthedSubscriptionsIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedSubscriptionsIdRoute: AuthedSubscriptionsIdRoute,
  AuthedSubscriptionsNewRoute: AuthedSubscriptionsNewRoute,
  AuthedSubscriptionsIndexRoute: AuthedSubscriptionsIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
